var fakeUser = [
  {
    id: 0,
    gender: "female",
    name: "Miss Cassandre Menard",
    country: "France",
    email: "cassandre.menard@example.com",
    age: 26,
    job: "Teacher",
    income: 12500,
    phone: "02-08-44-59-33",
    picture: {
      large: "https://randomuser.me/api/portraits/women/11.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/11.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/11.jpg",
    },
  },
  {
    id: 1,
    gender: "male",
    name: "Mr Johan Arnaud",
    country: "France",
    email: "johan.arnaud@example.com",
    age: 30,
    job: "Doctor",
    income: 32500,
    phone: "01-40-73-90-78",
    picture: {
      large: "https://randomuser.me/api/portraits/men/57.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/57.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/57.jpg",
    },
  },
  {
    id: 2,
    gender: "female",
    name: "Miss Vanesa Soto",
    country: "Spain",
    email: "vanesa.soto@example.com",
    age: 68,
    job: "Accountant",
    income: 22000,
    phone: "985-995-889",
    picture: {
      large: "https://randomuser.me/api/portraits/women/54.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/54.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/54.jpg",
    },
  },
  {
    id: 3,
    gender: "male",
    name: "Mr Mathias Larsen",
    country: "Denmark",
    email: "mathias.larsen@example.com",
    age: 74,
    job: "Management",
    income: 42000,
    phone: "48584737",
    picture: {
      large: "https://randomuser.me/api/portraits/men/95.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/95.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/95.jpg",
    },
  },
  {
    id: 4,
    gender: "female",
    name: "Ms Maria Pedersen",
    country: "Denmark",
    email: "maria.pedersen@example.com",
    age: 45,
    job: "Public Relation",
    income: 72000,
    phone: "42147735",
    picture: {
      large: "https://randomuser.me/api/portraits/women/74.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/74.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/74.jpg",
    },
  },
  {
    id: 5,
    gender: "male",
    name: "Mr Burkhardt Köllner",
    country: "Germany",
    email: "burkhardt.kollner@example.com",
    age: 47,
    job: "Administratoin",
    income: 45000,
    phone: "0621-2496454",
    picture: {
      large: "https://randomuser.me/api/portraits/men/89.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/89.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/89.jpg",
    },
  },
  {
    id: 6,
    gender: "female",
    name: "Ms Angela Frazier",
    country: "United Kingdom",
    email: "angela.frazier@example.com",
    age: 38,
    job: "Architecture",
    income: 25000,
    phone: "017687 35190",
    picture: {
      large: "https://randomuser.me/api/portraits/women/87.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/87.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/87.jpg",
    },
  },
  {
    id: 7,
    gender: "male",
    name: "Mr Elijah Wood",
    country: "New Zealand",
    email: "elijah.wood@example.com",
    age: 51,
    job: "Business",
    income: 85000,
    phone: "(773)-428-8756",
    picture: {
      large: "https://randomuser.me/api/portraits/men/58.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/58.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/58.jpg",
    },
  },
  {
    id: 8,
    gender: "female",
    name: "Mrs Veera Salmi",
    country: "Finland",
    email: "veera.salmi@example.com",
    age: 38,
    job: "Architecture",
    income: 25000,
    phone: "08-481-699",
    picture: {
      large: "https://randomuser.me/api/portraits/women/6.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/6.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/6.jpg",
    },
  },

  {
    id: 9,
    gender: "male",
    name: "Mr Roope Heikkila",
    country: "Finland",
    email: "roope.heikkila@example.com",
    age: 72,
    job: "Financial Specialists",
    income: 73000,
    phone: "06-615-818",
    picture: {
      large: "https://randomuser.me/api/portraits/men/92.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/92.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/92.jpg",
    },
  },
  {
    id: 10,
    gender: "female",
    name: "Miss Alyssia Gerard",
    country: "France",
    email: "alyssia.gerard@example.com",
    age: 52,
    job: "Budget Analysts",
    income: 84000,
    phone: "04-39-62-37-55",
    picture: {
      large: "https://randomuser.me/api/portraits/women/33.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/33.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/33.jpg",
    },
  },
  {
    id: 11,
    gender: "male",
    name: "Mr Marcus Møller",
    country: "Denmark",
    email: "marcus.moller@example.com",
    age: 74,
    job: "Loan Officers",
    income: 65000,
    phone: "83797065",
    picture: {
      large: "https://randomuser.me/api/portraits/men/68.jpg",
      medium: "https://randomuser.me/api/portraits/med/men/68.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/men/68.jpg",
    },
  },
  {
    id: 12,
    gender: "female",
    name: "Mrs Montserrat Benitez",
    country: "Spain",
    email: "montserrat.benitez@example.com",
    age: 63,
    job: "Revenue Agents",
    income: 35000,
    phone: "994-950-058",
    picture: {
      large: "https://randomuser.me/api/portraits/women/93.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/93.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/93.jpg",
    },
  },
  {
    id: 13,
    gender: "female",
    name: "Ms Millie Kumar",
    country: "New Zealand",
    email: "millie.kumar@example.com",
    age: 64,
    job: "Information Analysts",
    income: 75000,
    phone: "(644)-097-2511",
    picture: {
      large: "https://randomuser.me/api/portraits/women/68.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/68.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/68.jpg",
    },
  },
  {
    id: 14,
    gender: "female",
    name: "Miss Raphaela Guhl",
    country: "Germany",
    email: "raphaela.guhl@example.com",
    age: 41,
    job: "Web Developer",
    income: 225000,
    phone: "0666-6004409",
    picture: {
      large: "https://randomuser.me/api/portraits/women/80.jpg",
      medium: "https://randomuser.me/api/portraits/med/women/80.jpg",
      thumbnail: "https://randomuser.me/api/portraits/thumb/women/80.jpg",
    },
  },
];
export default fakeUser;
